version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-17005}:80"
    volumes:
      - ./.docker/site.dev.conf:/etc/nginx/conf.d/default.conf
      - php_volumes:/data/www
      - ../log/nginx:/var/log/nginx
    links:
      - "php"
  php:
    build: ./.docker/php
    environment:
      - SW_WORKER_NUM=10
      - SW_MAX_REQUEST=2000
    volumes:
      - php_volumes:/data/www
      - ./.docker/dev.ini:/usr/local/etc/php/conf.d/dev.ini
  php-queue:
    image: ${PHP_IMAGE:-docker.bs58i.baishancloud.com/oss/phalcon:dev}
    environment:
      - SW_WORKER_NUM=10
      - SW_MAX_REQUEST=2000
    volumes:
      - php_volumes:/data/www
    command: ["php", "artisan", "queue:work","--queue=${QUEUE_NAME:-default}","--tries=1"]
  mysqldb:
    image: mysql:5.6
    environment:
         - MYSQL_DATABASE=${MYSQL_DATABASE:-bookwarrior}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
         - MYSQL_USER=${MYSQL_USER:-root}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}
    ports:
      - "${MYSQL_PORT:-13306}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    user: "${UID}"
  transmission:
    image: linuxserver/transmission:latest
#    environment:
#         - PGID=${PGID:-bookwarrior}
#         - PUID=${PUID:-root}
#         - TZ=${TZ:-root}
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
#      - ./data/mysql:/config
      - ./data/transmimmsion/downloads:/downloads
      - ./data/transmimmsion/watch:/watch
      - ./.docker/settings.json:/config/settings.json
      - ./data/transmimmsion/torrents:/config/torrents
    user: "${UID}"
volumes:
  php_volumes:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
