version: '3.2'
services:
   redisdb:
      restart: always #设置自启动
      image: redis
#      ports:
#        - "${REDIS_IMAGE_PORT:-24916}:6379"
      volumes:
        - ../data/redis:/data
   web:
      restart: always #设置自启动
      container_name: busop
      image: nginx:latest
#      ports:
#        - "${HTTP_PORT:-17005}:80"
      volumes:
        - ./site.conf:/etc/nginx/conf.d/default.conf
        - php_volumes:/data/www
        - ../log/nginx:/var/log/nginx
      links:
        - "php"
   php:
      restart: always #设置自启动
      image: docker.bs58i.baishancloud.com/oss/busop:dev
      volumes:
        - php_volumes:/data/www
        - ../log:/data/www/log
        - ../cache:/data/www/cache
        - ../.env:/data/www/.env
volumes:
  php_volumes:
    driver: local
